server:
  port: 8081
spring:
  application:
    name: spring_boockshop_user_service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}