apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: ecco18/user-service:v12
          env:
            - name: DATABASE_USERNAME
              value: "database_username"
            - name: DATABASE_PASSWORD
              value: "database_password"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
  labels:
    monitor: user-service
spec:
  selector:
    app: user-service-app
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: user-nodeport-service
spec:
  type: NodePort
  selector:
    app: user-service-app
  ports:
    - protocol: TCP
      nodePort: 30082
      port: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-user-service
spec:
  rules:
    - host: demo.localdev.me
      http:
        paths:
          - path: /api/v1/users
            backend:
              service:
                name: user-app-service
                port:
                  number: 80
            pathType: Prefix
  ingressClassName: nginx